// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $dashboard from "./routes/dashboard.tsx";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $notifications from "./routes/notifications.tsx";
import * as $projects_id_ from "./routes/projects/[id].tsx";
import * as $projects_index from "./routes/projects/index.tsx";
import * as $settings from "./routes/settings.tsx";
import * as $signup from "./routes/signup.tsx";
import * as $tasks from "./routes/tasks.tsx";
import * as $CommentBox from "./islands/CommentBox.tsx";
import * as $ConfirmDialog from "./islands/ConfirmDialog.tsx";
import * as $DashboardClient from "./islands/DashboardClient.tsx";
import * as $InviteMemberModal from "./islands/InviteMemberModal.tsx";
import * as $KanbanBoard from "./islands/KanbanBoard.tsx";
import * as $LoginForm from "./islands/LoginForm.tsx";
import * as $NotificationDropdown from "./islands/NotificationDropdown.tsx";
import * as $NotificationsClient from "./islands/NotificationsClient.tsx";
import * as $ProjectCreateModal from "./islands/ProjectCreateModal.tsx";
import * as $ProjectDetailClient from "./islands/ProjectDetailClient.tsx";
import * as $ProjectsClient from "./islands/ProjectsClient.tsx";
import * as $SearchCommand from "./islands/SearchCommand.tsx";
import * as $SettingsClient from "./islands/SettingsClient.tsx";
import * as $SignupForm from "./islands/SignupForm.tsx";
import * as $SystemStatus from "./islands/SystemStatus.tsx";
import * as $TaskCreateModal from "./islands/TaskCreateModal.tsx";
import * as $TaskDetailModal from "./islands/TaskDetailModal.tsx";
import * as $TaskEditModal from "./islands/TaskEditModal.tsx";
import * as $TaskFilters from "./islands/TaskFilters.tsx";
import * as $TasksClient from "./islands/TasksClient.tsx";
import * as $ThemeToggle from "./islands/ThemeToggle.tsx";
import * as $ToastProvider from "./islands/ToastProvider.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/dashboard.tsx": $dashboard,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
    "./routes/notifications.tsx": $notifications,
    "./routes/projects/[id].tsx": $projects_id_,
    "./routes/projects/index.tsx": $projects_index,
    "./routes/settings.tsx": $settings,
    "./routes/signup.tsx": $signup,
    "./routes/tasks.tsx": $tasks,
  },
  islands: {
    "./islands/CommentBox.tsx": $CommentBox,
    "./islands/ConfirmDialog.tsx": $ConfirmDialog,
    "./islands/DashboardClient.tsx": $DashboardClient,
    "./islands/InviteMemberModal.tsx": $InviteMemberModal,
    "./islands/KanbanBoard.tsx": $KanbanBoard,
    "./islands/LoginForm.tsx": $LoginForm,
    "./islands/NotificationDropdown.tsx": $NotificationDropdown,
    "./islands/NotificationsClient.tsx": $NotificationsClient,
    "./islands/ProjectCreateModal.tsx": $ProjectCreateModal,
    "./islands/ProjectDetailClient.tsx": $ProjectDetailClient,
    "./islands/ProjectsClient.tsx": $ProjectsClient,
    "./islands/SearchCommand.tsx": $SearchCommand,
    "./islands/SettingsClient.tsx": $SettingsClient,
    "./islands/SignupForm.tsx": $SignupForm,
    "./islands/SystemStatus.tsx": $SystemStatus,
    "./islands/TaskCreateModal.tsx": $TaskCreateModal,
    "./islands/TaskDetailModal.tsx": $TaskDetailModal,
    "./islands/TaskEditModal.tsx": $TaskEditModal,
    "./islands/TaskFilters.tsx": $TaskFilters,
    "./islands/TasksClient.tsx": $TasksClient,
    "./islands/ThemeToggle.tsx": $ThemeToggle,
    "./islands/ToastProvider.tsx": $ToastProvider,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
